import { SITE } from "./site";

/** Shared wording: edit here to update every place using the same label. */
export const COMMON = {
  brand: {
    title: `${SITE.name} — ${SITE.tagline}`,
    homeLabel: `${SITE.name} Home`,
    logoAlt: `${SITE.name} Logo`,
  },
  actions: {
    startProject: "Start a project",
    goTo: (page: string) => `Go to ${page}`,
  },
  pages: {
    home: "Home",
    about: "About",
    contact: "Contact",
    work: "Work",
    services: "Services",
    ideas: "Ideas",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
  },
  channels: {
    whatsapp: "WhatsApp",
    directEmail: "Direct Email",
  },
  process: {
    strategy: "Strategy",
    design: "Design",
    develop: "Develop",
    launch: "Launch",
  },
  labels: {
    direct: "Direct",
    zero: "Zero",
    workHighlight: "Work.",
    performance: "Performance",
    techStack: "Tech Stack",
    productionReady: "Production-Ready",
    subSecondSpeed: "Sub-Second Speed",
    projectReview: "Project Review",
    guaranteedSla: "Guaranteed SLA",
    projectsDelivered: "Projects Delivered",
    businessGoals: "Business Goals",
    designTokens: "Design Tokens",
    designSystems: "Design Systems",
    cleanArchitecture: "Clean Architecture",
    realResults: "Real results.",
    prototypes: "Prototypes",
    architecture: "Architecture",
    ssl: "SSL",
    active: "Active",
    uptime: "Uptime",
    scalableCloud: "Scalable Cloud",
    mobileWeb: "Mobile & Web",
    mobilePlatforms: "iOS • Android • React",
    secureScalable: "Secure & Scalable",
    fullCodeOwnership: "Full Code Ownership",
    paymentGateway: "Payment Gateway",
    performant: "Performant",
    users: "Users",
    iosAndroid: "iOS & Android",
    offlineSync: "Offline Sync",
    crossPlatform: "Cross-Platform",
    uiUxDesign: "UI/UX Design",
    legacyModernization: "Legacy Modernization",
  },
  serviceNames: {
    websites: "Websites",
    webApplications: "Web applications",
    ecommerce: "E-commerce",
    mobileApps: "Mobile apps",
    saas: "SaaS products",
    branding: "Branding & identity",
    uiUx: "UI/UX design",
    customSoftware: "Custom software",
    webAppsFilter: "Web Apps",
    mobileAppsFilter: "Mobile Apps",
    webApplicationsTitle: "Web Applications",
  },
  categories: {
    frontend: "Frontend & Web",
    mobile: "Mobile",
    backend: "Backend & APIs",
    database: "Database & Cloud",
    design: "Design & Tools",
    clientInterface: "Client Interface",
    coreSystems: "Core Systems",
    foundation: "Foundation",
  },
  status: {
    inProgress: "Work In Progress",
    comingSoon: "Coming Soon",
  },
  symbols: {
    bullet: "•",
    sparkle: "✦",
    hollowSparkle: "✧",
    typeSample: "Aa",
    slash: "/",
  },
  technology: {
    nextjs: "Next.js",
    nextjs16: "Next.js 16",
    react: "React",
    tailwind: "Tailwind CSS",
    typescript: "TypeScript",
    reactNative: "React Native",
    nodejs: "Node.js",
    postgres: "PostgreSQL",
    supabase: "Supabase",
    prisma: "Prisma",
    prismaOrm: "Prisma ORM",
    redis: "Redis",
    whatsappApi: "WhatsApp API",
    flutter: "Flutter",
    swift: "Swift",
    kotlin: "Kotlin",
    expo: "Expo",
    python: "Python",
    fastapi: "FastAPI",
    aws: "AWS",
    docker: "Docker",
    vercel: "Vercel",
    cloudflare: "Cloudflare",
    figma: "Figma",
    photoshop: "Photoshop",
    illustrator: "Illustrator",
    canva: "Canva",
    stripe: "Stripe",
    razorpay: "Razorpay",
    typescriptTag: "<TypeScript />",
    fastapiTag: "<FastAPI />",
  },
} as const;
