import { TechCategory, TechItem, TECH_CATEGORIES } from '@/types/tech';
import { type AnimatedIconName } from '@/components/ui/animated-icon';

export const CATEGORIES = TECH_CATEGORIES;
export type Category = TechCategory;

export const CATEGORY_ICONS: Record<Category, AnimatedIconName> = {
  "Frontend & Web": "laptop",
  Mobile: "smartphone",
  "Backend & APIs": "cpu",
  "Database & Cloud": "layers",
  "Design & Tools": "palette",
};

// ─── Curated Tech Stack (Zero Redundancy — Exactly 1 Category Each) ───────────

export const TECH_STACK: TechItem[] = [
  // ── Frontend & Web (6) ───────────────────────────────────────────────────────
  {
    name: "React",
    slug: "react",
    category: "Frontend & Web",
    description: "Component based UI engine for modern web applications.",
    badge: "UI Library",
    dotColor: "#F43F5E", // pink / rose dot
    accentColor: "#61DAFB",
    learnMoreUrl: "https://react.dev",
  },
  {
    name: "Next.js",
    slug: "nextjs",
    category: "Frontend & Web",
    description: "Fullstack React framework with enterprise grade performance.",
    badge: "React Framework",
    dotColor: "#10B981", // emerald / mint dot
    accentColor: "#000000",
    learnMoreUrl: "https://nextjs.org",
    invertInDark: true,
  },
  {
    name: "Vue.js",
    slug: "vuejs",
    category: "Frontend & Web",
    description: "Progressive framework for flexible and scalable interfaces.",
    badge: "Progressive Framework",
    dotColor: "#F59E0B", // amber / yellow dot
    accentColor: "#4FC08D",
    learnMoreUrl: "https://vuejs.org",
  },
  {
    name: "TypeScript",
    slug: "typescript",
    category: "Frontend & Web",
    description: "Type-safe JavaScript for better and scalable code.",
    badge: "Type System",
    dotColor: "#3B82F6", // sky blue dot
    accentColor: "#3178C6",
    learnMoreUrl: "https://www.typescriptlang.org",
  },
  {
    name: "Tailwind CSS",
    slug: "tailwindcss",
    category: "Frontend & Web",
    description: "Utility-first CSS for rapid and consistent designs.",
    badge: "Utility CSS",
    dotColor: "#F59E0B", // amber dot
    accentColor: "#06B6D4",
    learnMoreUrl: "https://tailwindcss.com",
  },
  {
    name: "Vite",
    slug: "vite",
    category: "Frontend & Web",
    description: "Next-generation bundler with lightning fast dev experience.",
    badge: "Bundler",
    dotColor: "#A855F7", // purple dot
    accentColor: "#646CFF",
    learnMoreUrl: "https://vite.dev",
  },

  // ── Mobile (5) ───────────────────────────────────────────────────────────────
  {
    name: "React Native",
    slug: "reactnative",
    category: "Mobile",
    description: "Cross-platform mobile apps for iOS and Android.",
    badge: "Cross-Platform",
    dotColor: "#38BDF8",
    accentColor: "#61DAFB",
    learnMoreUrl: "https://reactnative.dev",
  },
  {
    name: "Flutter",
    slug: "flutter",
    category: "Mobile",
    description: "Multi-platform UI toolkit crafted with Dart engine.",
    badge: "UI Toolkit",
    dotColor: "#0284C7",
    accentColor: "#02569B",
    learnMoreUrl: "https://flutter.dev",
  },
  {
    name: "Swift",
    slug: "swift",
    category: "Mobile",
    description: "High-performance native apps for Apple ecosystem.",
    badge: "Native iOS",
    dotColor: "#F97316",
    accentColor: "#F05138",
    learnMoreUrl: "https://developer.apple.com/swift",
  },
  {
    name: "Kotlin",
    slug: "kotlin",
    category: "Mobile",
    description: "Modern type-safe native development for Android.",
    badge: "Native Android",
    dotColor: "#8B5CF6",
    accentColor: "#7F52FF",
    learnMoreUrl: "https://kotlinlang.org",
  },
  {
    name: "Expo",
    slug: "expo",
    category: "Mobile",
    description: "Universal React Native tooling and managed workflow.",
    badge: "Mobile Toolchain",
    dotColor: "#10B981",
    accentColor: "#000020",
    learnMoreUrl: "https://expo.dev",
    invertInDark: true,
  },

  // ── Backend & APIs (5) ───────────────────────────────────────────────────────
  {
    name: "Node.js",
    slug: "nodejs",
    category: "Backend & APIs",
    description: "Event-driven asynchronous JavaScript backend runtime.",
    badge: "JS Runtime",
    dotColor: "#22C55E",
    accentColor: "#339933",
    learnMoreUrl: "https://nodejs.org",
  },
  {
    name: "Nest.js",
    slug: "nestjs",
    category: "Backend & APIs",
    description: "Enterprise-grade TypeScript modular backend architecture.",
    badge: "Node.js Framework",
    dotColor: "#E11D48",
    accentColor: "#E0234E",
    learnMoreUrl: "https://nestjs.com",
  },
  {
    name: "Python",
    slug: "python",
    category: "Backend & APIs",
    description: "Versatile backend powerhouse and AI integration engine.",
    badge: "Language",
    dotColor: "#3B82F6",
    accentColor: "#3776AB",
    learnMoreUrl: "https://www.python.org",
  },
  {
    name: "FastAPI",
    slug: "fastapi",
    category: "Backend & APIs",
    description: "High-performance async API microservices with Python.",
    badge: "Python Framework",
    dotColor: "#06B6D4",
    accentColor: "#05998B",
    learnMoreUrl: "https://fastapi.tiangolo.com",
  },
  {
    name: "GraphQL",
    slug: "graphql",
    category: "Backend & APIs",
    description: "Declarative precision query language for modern APIs.",
    badge: "Query Language",
    dotColor: "#EC4899",
    accentColor: "#E10098",
    learnMoreUrl: "https://graphql.org",
  },

  // ── Database & Cloud (9) ─────────────────────────────────────────────────────
  {
    name: "PostgreSQL",
    slug: "postgresql",
    category: "Database & Cloud",
    description: "Rock-solid open-source relational database.",
    badge: "Relational DB",
    dotColor: "#3B82F6",
    accentColor: "#4169E1",
    learnMoreUrl: "https://www.postgresql.org",
  },
  {
    name: "Supabase",
    slug: "supabase",
    category: "Database & Cloud",
    description: "Serverless open-source Postgres, Auth & Realtime.",
    badge: "BaaS",
    dotColor: "#10B981",
    accentColor: "#3ECF8E",
    learnMoreUrl: "https://supabase.com",
  },
  {
    name: "MongoDB",
    slug: "mongodb",
    category: "Database & Cloud",
    description: "Flexible schema-free document database at scale.",
    badge: "NoSQL DB",
    dotColor: "#22C55E",
    accentColor: "#47A248",
    learnMoreUrl: "https://www.mongodb.com",
  },
  {
    name: "Redis",
    slug: "redis",
    category: "Database & Cloud",
    description: "Ultra-fast in-memory cache and real-time messaging.",
    badge: "In-Memory Store",
    dotColor: "#EF4444",
    accentColor: "#FF4438",
    learnMoreUrl: "https://redis.io",
  },
  {
    name: "Prisma",
    slug: "prisma",
    category: "Database & Cloud",
    description: "Next-gen type-safe ORM for database modeling.",
    badge: "ORM",
    dotColor: "#6366F1",
    accentColor: "#2D3748",
    learnMoreUrl: "https://www.prisma.io",
    invertInDark: true,
  },
  {
    name: "AWS",
    slug: "aws",
    category: "Database & Cloud",
    description: "World-class resilient global cloud infrastructure.",
    badge: "Cloud Provider",
    dotColor: "#F59E0B",
    accentColor: "#FF9900",
    learnMoreUrl: "https://aws.amazon.com",
  },
  {
    name: "Docker",
    slug: "docker",
    category: "Database & Cloud",
    description: "Standardized lightweight containerized deployments.",
    badge: "Containerization",
    dotColor: "#0284C7",
    accentColor: "#2496ED",
    learnMoreUrl: "https://www.docker.com",
  },
  {
    name: "Vercel",
    slug: "vercel",
    category: "Database & Cloud",
    description: "Edge compute platform optimized for frontend scale.",
    badge: "Deployment Platform",
    dotColor: "#111827",
    accentColor: "#000000",
    learnMoreUrl: "https://vercel.com",
    invertInDark: true,
  },
  {
    name: "Cloudflare",
    slug: "cloudflare",
    category: "Database & Cloud",
    description: "Global edge CDN, security shield & edge workers.",
    badge: "Edge Network",
    dotColor: "#F97316",
    accentColor: "#F6821F",
    learnMoreUrl: "https://www.cloudflare.com",
  },


  // ── Design & Tools (11) ──────────────────────────────────────────────────────
  {
    name: "Figma",
    slug: "figma",
    category: "Design & Tools",
    description: "Collaborative interface and system design workspace.",
    badge: "UI/UX Design",
    dotColor: "#F43F5E",
    accentColor: "#F24E1E",
    learnMoreUrl: "https://www.figma.com",
  },
  {
    name: "Photoshop",
    slug: "photoshop",
    category: "Design & Tools",
    description: "Industry standard for creative image synthesis.",
    badge: "Raster Graphics",
    dotColor: "#0284C7",
    accentColor: "#31A8FF",
    learnMoreUrl: "https://www.adobe.com/products/photoshop.html",
  },
  {
    name: "Illustrator",
    slug: "illustrator",
    category: "Design & Tools",
    description: "Precision vector illustration and identity branding.",
    badge: "Vector Graphics",
    dotColor: "#F97316",
    accentColor: "#FF9A00",
    learnMoreUrl: "https://www.adobe.com/products/illustrator.html",
  },
  {
    name: "Canva",
    slug: "canva",
    category: "Design & Tools",
    description: "Fast asset creation and marketing collateral design.",
    badge: "Graphic Design",
    dotColor: "#06B6D4",
    accentColor: "#00C4CC",
    learnMoreUrl: "https://www.canva.com",
  },
  {
    name: "Antigravity",
    slug: "antigravity",
    category: "Design & Tools",
    description: "Agentic AI development platform & next-gen IDE.",
    badge: "Agentic IDE",
    dotColor: "#3B82F6",
    accentColor: "#3186FF",
    learnMoreUrl: "https://antigravity.google",
  },
  {
    name: "Git",
    slug: "git",
    category: "Design & Tools",
    description: "Distributed source control for agile teams.",
    badge: "Version Control",
    dotColor: "#F43F5E",
    accentColor: "#F05032",
    learnMoreUrl: "https://git-scm.com",
  },
  {
    name: "VS Code",
    slug: "vscode",
    category: "Design & Tools",
    description: "Extensible code editing environment for engineers.",
    badge: "Code Editor",
    dotColor: "#0284C7",
    accentColor: "#007ACC",
    learnMoreUrl: "https://code.visualstudio.com",
  },
  {
    name: "Postman",
    slug: "postman",
    category: "Design & Tools",
    description: "Collaborative API prototyping, testing and mocking.",
    badge: "API Platform",
    dotColor: "#F97316",
    accentColor: "#FF6C37",
    learnMoreUrl: "https://www.postman.com",
  },
  {
    name: "Stripe",
    slug: "stripe",
    category: "Design & Tools",
    description: "Global payment processing and subscription billing.",
    badge: "Payment Gateway",
    dotColor: "#6366F1",
    accentColor: "#635BFF",
    learnMoreUrl: "https://stripe.com",
  },
  {
    name: "Razorpay",
    slug: "razorpay",
    category: "Design & Tools",
    description: "Unified payment gateway and digital banking.",
    badge: "Payment Gateway",
    dotColor: "#0284C7",
    accentColor: "#2B84EA",
    learnMoreUrl: "https://razorpay.com",
  },
  {
    name: "GitHub Actions",
    slug: "githubactions",
    category: "Design & Tools",
    description: "Automated CI/CD pipelines and deployment workflows.",
    badge: "CI/CD",
    dotColor: "#2563EB",
    accentColor: "#2088FF",
    learnMoreUrl: "https://github.com/features/actions",
  },
];

export const TECH_STACK_SECTION_CONTENT = {
  eyebrow: "OUR TECH STACK",
  title: "Modern tools.",
  highlightedText: "Real results.",
  descriptionLine1: "Battle-tested tools chosen for reliability, performance, and long-term maintainability —",
  descriptionLine2: "not just trends.",
  footerNote: "We choose tools that fit your project — not the other way around.",
};
